// Auto-replace brand mark with logo
new MutationObserver(()=>{const mark=document.querySelector('.card-top .brand-mark');if(mark){const logo=document.createElement('img');logo.className='card-logo';logo.src='logo/logo.png';logo.alt='ZCIEA logo';mark.replaceWith(logo)}}).observe(document.querySelector('#modal-root'),{childList:true,subtree:true});

// Photo editor - adds file input to member form
const photoEditor=()=>{const form=$('#member-form');if(!form||$('#member-photo'))return;const field=document.createElement('div');field.className='field full-width';field.innerHTML='<label>Member photo<input id="member-photo" type="file" accept="image/jpeg,image/png,image/webp" /><small class="muted">JPG, PNG or WebP. Maximum 5 MB.</small></label><div id="photo-preview" class="photo-upload-preview"></div>';form.querySelector('.form-grid').append(field);$('#member-photo').onchange=e=>{const file=e.target.files[0];if(!file)return;if(file.size>5*1024*1024){toast('Photo must be smaller than 5 MB.');e.target.value='';return}const reader=new FileReader();reader.onload=event=>{const image=new Image();image.onload=()=>{const scale=Math.min(1,600/Math.max(image.width,image.height)),canvas=document.createElement('canvas');canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);form.dataset.photo=canvas.toDataURL('image/jpeg',.82);$('#photo-preview').innerHTML=`<img src="${form.dataset.photo}" alt="Selected member photo" />`};image.src=event.target.result};reader.readAsDataURL(file)}};
new MutationObserver(photoEditor).observe(document.querySelector('#modal-root'),{childList:true});

// Form submit handler
document.addEventListener('submit',e=>{if(e.target.id!=='member-form')return;e.preventDefault();e.stopImmediatePropagation();const form=e.target,data=Object.fromEntries(new FormData(form)),wasEditing=Boolean(editingId);if(wasEditing){members=members.map(x=>x.id===editingId?{...x,...data,photo:form.dataset.photo||x.photo||''}:x)}else{const today=new Date().toISOString().slice(0,10),expiry=new Date(today);expiry.setFullYear(expiry.getFullYear()+5);members.push({id:`ZC-26${String(members.length+1).padStart(3,'0')}`,...data,photo:form.dataset.photo||'',joined:today,expiryDate:expiry.toISOString().slice(0,10),subscriptionAmount:parseFloat(data.subscriptionAmount)||6.00})}save();closeModal();render();toast(wasEditing?'Member updated.':'Member registered.')},true);

// Seed data
const seedMembers=[
  {id:'ZC-26001',fullName:'Mavis Chipo',idNumber:'63-184920 Q 63',dob:'1988-04-12',gender:'Female',trade:'Fresh produce vendor',territory:'Mbare',contact:'+263 77 123 4567',subscription:'Active',joined:'2026-01-12',expiryDate:'2031-01-12',subscriptionAmount:6.00},
  {id:'ZC-26002',fullName:'Tendai Moyo',idNumber:'28-093842 P 28',dob:'1979-09-28',gender:'Male',trade:'Shoe repair',territory:'Highfield',contact:'+263 71 884 2301',subscription:'Active',joined:'2026-02-04',expiryDate:'2031-02-04',subscriptionAmount:6.00},
  {id:'ZC-26003',fullName:'Rudo Ncube',idNumber:'12-748392 T 12',dob:'1995-06-19',gender:'Female',trade:'Clothing trader',territory:'Mupedzanhamo',contact:'+263 78 442 9002',subscription:'Pending',joined:'2026-02-17',expiryDate:'2031-02-17',subscriptionAmount:6.00},
  {id:'ZC-26004',fullName:'Brian Dube',idNumber:'63-929182 L 63',dob:'1968-11-02',gender:'Male',trade:'Carpentry',territory:'Glen View',contact:'+263 77 902 1120',subscription:'Expired',joined:'2025-12-19',expiryDate:'2030-12-19',subscriptionAmount:6.00},
  {id:'ZC-26005',fullName:'Nyarai Manyika',idNumber:'08-391820 V 08',dob:'1991-02-25',gender:'Female',trade:'Hairdresser',territory:'Chitungwiza',contact:'+263 77 319 7721',subscription:'Active',joined:'2026-03-01',expiryDate:'2031-03-01',subscriptionAmount:6.00}
];

let members=JSON.parse(localStorage.getItem('zciea-members')||'null')||seedMembers;
let currentPage='overview';
let editingId=null;
let memberPageNumber=1;
const memberPageSize=50;
const $=s=>document.querySelector(s);
const esc=v=>String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));

function save(){localStorage.setItem('zciea-members',JSON.stringify(members));$('#nav-count').textContent=members.length;$('#total-members').innerHTML=`● <b>${members.length.toLocaleString()}</b> total members`}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2800)}

function login(){const username=$('#username').value.trim(),password=$('#password').value;if(username==='admin'&&password==='admin123'){$('#login-error').classList.add('hidden');$('#login-view').classList.add('hidden');$('#app-view').classList.remove('hidden');save();render()}else $('#login-error').classList.remove('hidden')}

$('#login-btn').addEventListener('click',login);
$('#password').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();login()}});
$('#logout-btn').onclick=()=>{location.reload()};

document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>{currentPage=b.dataset.page;document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n===b));render()});
$('#header-add').onclick=()=>openMember();

function render(){const titles={overview:['OVERVIEW','Good morning, Admin'],members:['MEMBER DIRECTORY','All members'],reports:['INSIGHTS','Registry reports'],outreach:['OUTREACH','Reach your members'],import:['DATA TOOLS','Import / export']};$('#page-kicker').textContent=titles[currentPage][0];$('#page-title').textContent=titles[currentPage][1];const pages={overview:overview,members:memberPage,reports:reports,outreach:outreach,import:importPage};$('#page-content').innerHTML=pages[currentPage]();if(currentPage==='members')bindMemberSearch();if(currentPage==='outreach')bindOutreach();}

function overview(){const active=members.filter(m=>m.subscription==='Active').length,female=members.filter(m=>m.gender==='Female').length;return `<div class="content"><div class="section-heading"><div><span class="eyebrow">REGISTRY SNAPSHOT</span><h2>At a glance</h2></div><button class="btn secondary" onclick="exportData('csv')">⇩ Export CSV</button></div><div class="stats-grid"><div class="stat-card"><small>TOTAL MEMBERS</small><strong>${members.length}</strong><span>All registered members</span></div><div class="stat-card"><small>ACTIVE SUBSCRIPTIONS</small><strong>${active}</strong><span>${members.length?Math.round(active/members.length*100):0}% of registry</span></div><div class="stat-card"><small>WOMEN MEMBERS</small><strong>${female}</strong><span>${members.length?Math.round(female/members.length*100):0}% representation</span></div><div class="stat-card"><small>TERRITORIES</small><strong>${new Set(members.map(m=>m.territory)).size}</strong><span>Communities represented</span></div></div><div class="grid-2"><div class="panel"><div class="panel-head"><div><span class="eyebrow">MEMBERSHIP</span><h3>New registrations</h3></div><span class="muted">Last 6 months</span></div><div class="chart">${[22,38,30,56,47,72].map((n,i)=>`<div class="bar-wrap"><div class="bar" style="height:${n}%"></div><span class="bar-label">${['MAR','APR','MAY','JUN','JUL','AUG'][i]}</span></div>`).join('')}</div></div><div class="panel"><div class="panel-head"><div><span class="eyebrow">COMPOSITION</span><h3>Gender split</h3></div></div><div class="donut-wrap"><div class="donut"></div><div class="legend"><span>Women · ${female}</span><span>Men · ${members.length-female}</span><span>Other · 0</span></div></div></div></div><div class="panel table-panel"><div class="panel-head"><div><span class="eyebrow">RECENTLY ADDED</span><h3>Latest members</h3></div><button class="btn secondary" onclick="currentPage='members';render()">View directory ↗</button></div>${memberTable(members.slice(-5).reverse())}</div></div>`}

function memberTable(list,actions=true){if(!list.length)return '<div class="empty">No members found.</div>';return `<div class="table-wrap"><table class="data-table"><thead><tr><th>MEMBER</th><th>MEMBERSHIP NO.</th><th>GENDER</th><th>TRADE</th><th>TERRITORY</th><th>STATUS</th>${actions?'<th></th>':''}</tr></thead><tbody>${list.map(m=>`<tr><td><div class="member-name">${esc(m.fullName)}</div><div class="member-sub">${esc(m.contact)}</div></td><td><span class="eyebrow">${m.id}</span></td><td>${esc(m.gender)}</td><td>${esc(m.trade)}</td><td>${esc(m.territory)}</td><td><span class="pill ${m.subscription==='Expired'?'expired':''}">${m.subscription}</span></td>${actions?`<td><button class="action-btn" title="View membership card" onclick="showCard('${m.id}')">▣</button><button class="action-btn" title="Edit" onclick="openMember('${m.id}')">✎</button><button class="action-btn" title="Delete" onclick="deleteMember('${m.id}')">×</button></td>`:''}</tr>`).join('')}</tbody></table></div>`}

function memberPage(){return `<div class="content"><div class="section-heading"><div><span class="eyebrow">${members.length} RECORDS</span><h2>Member directory</h2></div><button class="btn primary" onclick="openMember()">＋ Register member</button></div><div class="panel table-panel" style="margin-top:0"><div class="panel-head"><div><h3>All members</h3><p class="muted">Search, update, or issue an ID card.</p></div><div class="table-tools"><input class="search-input" id="member-search" placeholder="Search name, ID or territory..." /><select id="status-filter" class="search-input" style="width:130px"><option value="">All status</option><option>Active</option><option>Pending</option><option>Expired</option></select></div></div><div id="member-results"></div><div id="member-pagination" class="member-pagination"></div></div></div>`}

function bindMemberSearch(){let timer;const run=()=>{clearTimeout(timer);timer=setTimeout(()=>{memberPageNumber=1;renderMemberResults()},120)};$('#member-search').oninput=run;$('#status-filter').onchange=run;renderMemberResults()}

function renderMemberResults(){const q=($('#member-search')?.value||'').toLowerCase().trim(),s=$('#status-filter')?.value||'';const filtered=members.filter(m=>(!q||Object.values(m).some(v=>String(v).toLowerCase().includes(q)))&&(!s||m.subscription===s));const pageCount=Math.max(1,Math.ceil(filtered.length/memberPageSize));memberPageNumber=Math.min(memberPageNumber,pageCount);const start=(memberPageNumber-1)*memberPageSize;$('#member-results').innerHTML=memberTable(filtered.slice(start,start+memberPageSize));$('#member-pagination').innerHTML=`<span>Showing ${filtered.length?start+1:0}-${Math.min(start+memberPageSize,filtered.length)} of ${filtered.length}</span><div><button class="btn secondary" onclick="memberPageNumber--;renderMemberResults()" ${memberPageNumber===1?'disabled':''}>Previous</button><button class="btn secondary" onclick="memberPageNumber++;renderMemberResults()" ${memberPageNumber===pageCount?'disabled':''}>Next</button></div>`}

function reports(){const locations=[...new Set(members.map(m=>m.territory))].map(t=>[t,members.filter(m=>m.territory===t).length]).sort((a,b)=>b[1]-a[1]);const age=(d)=>Math.floor((Date.now()-new Date(d))/31557600000);const bands={'18–25':0,'26–35':0,'36–50':0,'51+':0};members.forEach(m=>{const a=age(m.dob);bands[a<=25?'18–25':a<=35?'26–35':a<=50?'36–50':'51+']++});return `<div class="content"><div class="section-heading"><div><span class="eyebrow">MEMBERSHIP INTELLIGENCE</span><h2>Reports</h2></div><button class="btn secondary" onclick="exportData('xlsx')">⇩ Download Excel</button></div><div class="report-filters"><select><option>All time</option><option>This year</option></select><select><option>All territories</option>${locations.map(x=>`<option>${x[0]}</option>`).join('')}</select></div><div class="grid-2" style="margin-top:0"><div class="panel"><div class="panel-head"><div><span class="eyebrow">LOCATION</span><h3>Members by territory</h3></div></div><div class="bars-list">${locations.slice(0,7).map(([n,v])=>`<div class="bar-line"><span>${esc(n)}</span><div class="bar-track"><div class="bar-fill" style="width:${Math.max(5,v/members.length*100)}%"></div></div><b>${v}</b></div>`).join('')}</div></div><div class="panel"><div class="panel-head"><div><span class="eyebrow">AGE PROFILE</span><h3>Members by age</h3></div></div><div class="bars-list">${Object.entries(bands).map(([n,v])=>`<div class="bar-line"><span>${n}</span><div class="bar-track"><div class="bar-fill" style="width:${Math.max(5,v/members.length*100)}%"></div></div><b>${v}</b></div>`).join('')}</div></div></div><div class="panel table-panel"><div class="panel-head"><div><span class="eyebrow">SUBSCRIPTION HEALTH</span><h3>Status breakdown</h3></div></div>${memberTable(members.slice(0,50),false)}<p class="muted report-limit">Showing the first 50 records. Search the complete registry from Members.</p></div></div>`}

function outreach(){return `<div class="content"><div class="section-heading"><div><span class="eyebrow">DIRECT COMMUNICATION</span><h2>Targeted outreach</h2></div></div><div class="outreach-layout"><div class="panel"><span class="eyebrow">1 · SELECT AUDIENCE</span><h3 style="margin-top:8px">Choose recipients</h3><select id="territory-target" class="search-input" style="margin-top:17px"><option value="">All members (${members.length})</option>${[...new Set(members.map(m=>m.territory))].map(t=>`<option>${t}</option>`).join('')}</select><p class="muted outreach-limit">Showing the first 100 members here. Territory targeting still applies to the full registry.</p><div class="recipient-list">${members.slice(0,100).map(m=>`<label class="recipient"><input type="checkbox" value="${m.id}" checked><div><b>${esc(m.fullName)}</b><small>${esc(m.territory)} · ${esc(m.contact)}</small></div></label>`).join('')}</div></div><div class="panel"><span class="eyebrow">2 · COMPOSE MESSAGE</span><h3 style="margin-top:8px">Send a notification</h3><label class="field">Subject<input id="message-subject" placeholder="e.g. Membership renewal reminder" /></label><label class="field">Message<textarea id="message-body" placeholder="Write your message to selected members..."></textarea></label><div class="notice">Messages are prepared for the selected members. Connect an SMS or email provider in production to deliver them directly.</div><div class="modal-actions"><button class="btn primary" id="send-message">Send notification ↗</button></div></div></div></div>`}

function bindOutreach(){$('#territory-target').onchange=e=>document.querySelectorAll('.recipient input').forEach(i=>i.checked=!e.target.value||members.find(m=>m.id===i.value).territory===e.target.value);$('#send-message').onclick=()=>{const selected=[...document.querySelectorAll('.recipient input:checked')].length;if(!$('#message-body').value.trim())return toast('Add a message before sending.');toast(`Notification queued for ${selected} member${selected===1?'':'s'}.`);$('#message-body').value='';$('#message-subject').value=''}}

function importPage(){return `<div class="content"><div class="section-heading"><div><span class="eyebrow">DATA MANAGEMENT</span><h2>Import / export</h2></div></div><div class="grid-2" style="margin-top:0"><div class="panel"><span class="eyebrow">IMPORT MEMBERS</span><h3 style="margin:8px 0">Bring in an Excel file</h3><div class="dropzone" style="margin-top:20px"><div style="font-size:28px;color:var(--teal)">⇧</div><strong>Choose an Excel or CSV file</strong><p>Columns should match: full name, ID number, date of birth, gender, trade, territory, contact number.</p><label class="btn primary" for="file-upload">Browse files</label><input class="file-input" id="file-upload" type="file" accept=".csv,.xlsx,.xls" /><div id="import-status"></div></div></div><div class="panel"><span class="eyebrow">EXPORT REGISTRY</span><h3 style="margin:8px 0">Take your data with you</h3><p class="muted" style="line-height:1.6">Export the complete membership registry for analysis, sharing, or backup.</p><div style="display:flex;gap:10px;margin-top:28px"><button class="btn primary" onclick="exportData('xlsx')">⇩ Excel workbook</button><button class="btn secondary" onclick="exportData('csv')">⇩ CSV file</button></div><div class="notice" style="margin-top:35px">${members.length} members are currently stored in this browser.</div></div></div></div>`}

function openMember(id){editingId=id||null;const m=members.find(x=>x.id===id)||{fullName:'',idNumber:'',dob:'',gender:'Female',trade:'',territory:'',contact:'',subscription:'Active',subscriptionAmount:6.00};const calcExpiry=(joined)=>{if(!joined)return '';const d=new Date(joined);d.setFullYear(d.getFullYear()+5);return d.toISOString().slice(0,10)};$('#modal-root').innerHTML=`<div class="modal-backdrop"><form class="modal" id="member-form"><div class="modal-head"><div><span class="eyebrow">${id?'UPDATE RECORD':'NEW REGISTRATION'}</span><h2>${id?'Edit member':'Register a member'}</h2></div><button type="button" class="close" onclick="closeModal()">×</button></div><div class="form-grid"><div class="field"><label>Full name<input name="fullName" required value="${esc(m.fullName)}" /></label></div><div class="field"><label>ID number<input name="idNumber" required value="${esc(m.idNumber)}" /></label></div><div class="field"><label>Date of birth<input name="dob" type="date" required value="${m.dob}" /></label></div><div class="field"><label>Gender<select name="gender"><option ${m.gender==='Female'?'selected':''}>Female</option><option ${m.gender==='Male'?'selected':''}>Male</option><option>Other</option></select></label></div><div class="field"><label>Trade / occupation<input name="trade" required value="${esc(m.trade)}" /></label></div><div class="field"><label>Territory / location<input name="territory" required value="${esc(m.territory)}" /></label></div><div class="field"><label>Contact number<input name="contact" required value="${esc(m.contact)}" /></label></div><div class="field"><label>Subscription status<select name="subscription"><option ${m.subscription==='Active'?'selected':''}>Active</option><option ${m.subscription==='Pending'?'selected':''}>Pending</option><option ${m.subscription==='Expired'?'selected':''}>Expired</option></select></label></div><div class="field"><label>Annual subscription amount ($)<input name="subscriptionAmount" type="number" step="0.01" value="${m.subscriptionAmount||6.00}" /></label></div></div><div class="modal-actions"><button class="btn secondary" type="button" onclick="closeModal()">Cancel</button><button class="btn primary">Save member ↗</button></div></form></div>`;photoEditor()}

function closeModal(){$('#modal-root').innerHTML='';editingId=null}

function deleteMember(id){if(confirm('Delete this member record?')){members=members.filter(m=>m.id!==id);save();render();toast('Member deleted.')}}

function showCard(id){const m=members.find(x=>x.id===id);const formatDate=(d)=>d?new Date(d).toLocaleDateString('en-ZA',{year:'numeric',month:'short',day:'numeric'}):'-';$('#modal-root').innerHTML=`<div class="modal-backdrop"><div class="modal cr80-modal"><div class="modal-head"><div><span class="eyebrow">MEMBERSHIP CARD</span><h2>CR-80 Format (84.1mm × 52.4mm)</h2></div><button class="close" onclick="closeModal()">×</button></div><div class="card-cr80"><div class="card-header"><img class="card-logo-cr80" src="logo/logo.png" alt="ZCIEA logo" /><div class="card-org-name"><strong>ZIMBABWE CHAMBER</strong><strong>INFORMAL ECONOMY</strong></div></div><div class="card-main"><div class="card-photo-section">${m.photo?`<img src="${m.photo}" class="card-photo" alt="Member photo" />`:
`<div class="photo-placeholder">${m.fullName.split(' ').map(x=>x[0]).join('').slice(0,2)}</div>`}</div><div class="card-details"><div class="detail-line"><label>FULL NAME</label><span>${esc(m.fullName)}</span></div><div class="detail-line"><label>ID NUMBER</label><span>${esc(m.idNumber)}</span></div><div class="detail-line"><label>GENDER</label><span>${esc(m.gender)}</span></div><div class="detail-line"><label>TERRITORY</label><span>${esc(m.territory)}</span></div><div class="detail-line"><label>VALID UNTIL</label><span>${formatDate(m.expiryDate)}</span></div></div><div class="card-qr-section"><div id="qr-${m.id}"></div></div></div><div class="card-footer-cr80">${m.id}</div></div><div class="modal-actions"><button class="btn secondary" onclick="window.print()">Print card ↗</button><button class="btn secondary" onclick="closeModal()">Close</button></div></div></div>`;new QRCode(document.getElementById(`qr-${m.id}`),{text:m.id,width:80,height:80,colorDark:'#0d756b',colorLight:'#ffffff'});}

function exportData(type){const rows=members.map(m=>({'Membership number':m.id,'Full name':m.fullName,'ID number':m.idNumber,'Date of birth':m.dob,Gender:m.gender,Trade:m.trade,Territory:m.territory,'Contact number':m.contact,'Registered':m.joined,'Expiry date':m.expiryDate,'Subscription status':m.subscription}));let blob,name;if(type==='xlsx'&&window.XLSX){const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),'Members');XLSX.writeFile(wb,'zciea-members.xlsx');toast('Excel workbook downloaded.');return}const csv=[Object.keys(rows[0]).join(','),...rows.map(r=>Object.values(r).map(v=>`"${String(v).replaceAll('"','""')}"`).join(','))].join('\n');blob=new Blob([csv],{type:'text/csv'});name='zciea-members.csv';const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();toast('CSV file downloaded.')}

const validateMember=(m,idx)=>{const errors=[];if(!m.fullName||m.fullName.toString().trim()==='')errors.push('Missing full name');if(!m.idNumber||m.idNumber.toString().trim()==='')errors.push('Missing ID number');if(!m.dob||m.dob.toString().trim()==='')errors.push('Missing date of birth');else if(!/^\d{4}-\d{2}-\d{2}$/.test(m.dob.toString().trim()))errors.push('Invalid date format (use YYYY-MM-DD)');if(!m.contact||m.contact.toString().trim()==='')errors.push('Missing contact number');if(!m.territory||m.territory.toString().trim()==='')errors.push('Missing territory');return{valid:errors.length===0,errors:errors,rowNum:idx+1}};

const checkDuplicates=(m)=>{const existing=members.find(x=>x.idNumber.toLowerCase()===m.idNumber.toString().trim().toLowerCase()||x.fullName.toLowerCase()===m.fullName.toString().trim().toLowerCase());return existing?{duplicate:true,existing:existing}:{duplicate:false}};

function openFieldMapping(rows){const headers=Object.keys(rows[0]);const fields=['fullName','idNumber','dob','gender','trade','territory','contact','subscription','subscriptionAmount'];let mapping={};$('#modal-root').innerHTML=`<div class="modal-backdrop"><form class="modal" id="mapping-form"><div class="modal-head"><div><span class="eyebrow">COLUMN MAPPING</span><h2>Map your data</h2></div><button type="button" class="close" onclick="closeModal()">×</button></div><div class="mapping-container">${fields.map(field=>`<div class="mapping-row"><label class="mapping-label"><span class="eyebrow">${field.toUpperCase()}</span></label><select class="mapping-select" data-field="${field}"><option value="">-- Select column --</option>${headers.map(h=>`<option value="${h}">${h}</option>`).join('')}</select></div>`).join('')}</div><div class="modal-actions"><button type="button" class="btn secondary" onclick="closeModal()">Cancel</button><button class="btn primary">Continue to preview ↗</button></div></form></div>`;document.querySelectorAll('.mapping-select').forEach(sel=>{sel.onchange=e=>mapping[sel.dataset.field]=e.target.value});document.getElementById('mapping-form').addEventListener('submit',e=>{e.preventDefault();openImportPreview(rows,mapping)},true)}

function openImportPreview(rows,mapping){const mapped=rows.map(r=>({fullName:r[mapping.fullName]||'',idNumber:r[mapping.idNumber]||'',dob:r[mapping.dob]||'',gender:r[mapping.gender]||'Female',trade:r[mapping.trade]||'',territory:r[mapping.territory]||'',contact:r[mapping.contact]||'',subscription:r[mapping.subscription]||'Pending',subscriptionAmount:parseFloat(r[mapping.subscriptionAmount])||6.00}));const validationResults=mapped.map(validateMember);const valid=validationResults.filter(r=>r.valid).length,errors=validationResults.filter(r=>!r.valid).length;let duplicates=0;mapped.forEach(m=>{if(checkDuplicates(m).duplicate)duplicates++});$('#modal-root').innerHTML=`<div class="modal-backdrop"><div class="modal" style="max-width:800px"><div class="modal-head"><div><span class="eyebrow">IMPORT PREVIEW</span><h2>Review before importing</h2></div><button class="close" onclick="closeModal()">×</button></div><div class="preview-stats"><div class="stat ${valid>0?'success':'error'}"><strong>${valid}</strong><span>Valid records</span></div><div class="stat ${errors>0?'error':'success'}"><strong>${errors}</strong><span>Errors</span></div><div class="stat ${duplicates>0?'warning':'success'}"><strong>${duplicates}</strong><span>Possible duplicates</span></div><div class="stat"><strong>${mapped.length}</strong><span>Total records</span></div></div>${validationResults.filter(r=>!r.valid).map(r=>`<div class="alert error"><strong>Row ${r.rowNum}</strong>${r.errors.map(e=>`<div class="error-item">• ${e}</div>`).join('')}</div>`).join('')}<div class="import-preview-scroll">${memberTable(mapped.slice(0,20),false)}</div><p class="muted report-limit">${mapped.length>20?`Showing first 20 of ${mapped.length} records`:'All records shown'}</p><div class="modal-actions"><button class="btn secondary" onclick="closeModal()">Cancel</button><button class="btn primary" ${errors>0||duplicates>0?'disabled':''} onclick="confirmImport('${btoa(JSON.stringify(mapped))}')">Import ${valid} members ↗</button></div></div></div>`}

function confirmImport(encoded){const mapped=JSON.parse(atob(encoded));members.push(...mapped);save();render();closeModal();toast(`${mapped.length} members imported successfully.`)}

function importFile(file){const reader=new FileReader();reader.onload=e=>{try{const data=file.name.endsWith('.csv')?CSV.parse(e.target.result):XLSX.read(e.target.result,{type:'array'}).Sheets[XLSX.read(e.target.result,{type:'array'}).SheetNames[0]];const json=XLSX.utils.sheet_to_json(data||XLSX.utils.aoa_to_sheet(CSV.parse(e.target.result)));if(json.length===0){toast('File is empty or could not be read.');return}openFieldMapping(json)}catch(err){toast('Error reading file. Please check the format.')}};file.name.endsWith('.csv')?reader.readAsText(file):reader.readAsArrayBuffer(file)}

document.addEventListener('change',e=>{if(e.target.id==='file-upload'&&e.target.files[0])importFile(e.target.files[0])});
